# Create with conda env create -f environment.ym
# Activate with conda activate puzzle
name: puzzle
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pylint
  - pip:
    - jinja2